
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_versioning:
    runs-on: ubuntu-latest
    container: node:latest
      env:
        GITHUB_TOKEN: 338206d4443e6d1aadb9cd1de77943fa54ce8944
    steps:
      - name: Installation
        run: |
          echo "Rodando primeiro comando"
          npx semantic-release
