
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create_versioning:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Git_Checkout
        uses: actions/checkout@v1     
      - name: Create_Release
        run: |
          ls
          npx semantic-release
